apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.instanceName }}
  labels:
    app: {{ .Values.instanceName }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.instanceName }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
{{ if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
{{ end }}
